### ISSUE TITLE
KeyError: 'component' message 

### ISSUE THREAD

**Issue by rdek** [multiservicio/sonarqube-exporter#2]
mineuser@jbehave:/opt/sonarqube-exporter > python3 sonar-client.py
com.g-dev.jbehave:BUM_PLUS GWgG1xtnhxQdf62aHxuD
com.g-dev.jbehave:nokey AXfjcTCwhxWdx62aHguI
com.g-dev.jbehave:Vuln_Node AKqKAsdjPjpAgud
Traceback (most recent call last):
  File "sonar-client.py", line 115, in <module>
    measures = client.get_measures_by_component_id(uri + '?' + component_id_query_param + '&' + metric_key_query_param)
  File "sonar-client.py", line 54, in get_measures_by_component_id
    return data['component']['measures']
KeyError: 'component'
mineuser@jbehave:/opt/sonarqube-exporter >

**Comment by udayakumard** [comment]
I am also getting following error,

(u'XXXXXXXX', u'AWq2N_VmFhVrNE-Y-dDK')
Traceback (most recent call last):
  File "sonar-client.py", line 107, in <module>
    measures = client.get_measures_by_component_id(uri + '?' + component_id_query_param + '&' + metric_key_query_param)
  File "sonar-client.py", line 46, in get_measures_by_component_id
    return data['component']['measures']
KeyError: 'component'

**Comment by vakaobr** [comment]
I think the problem is because new versions of sonar introduced STRING types on metrics exported.

For now, we just find one metric called "new_development_cost" using this type.

So, we've managed to solve that with:

```for metric in metrics:
    if metric != "new_development_cost":
        comma_separated_metrics += metric + ','```

**Comment by vakaobr** [comment]
I think the problem is related to new versions of sonarqube have introduced metrics with type STRING.

For now, we just found one metric called "new_development_cost" using this type.

We've managed to solve it with:

```if metric != "new_development_cost":
        comma_separated_metrics += metric + ','

**Comment by vakaobr** [comment]
I think the problem is related to new versions of sonarqube have introduced metrics with type STRING.

For now, we just found one metric called "new_development_cost" using this type.

We've managed to solve it with:
````if metric != "new_development_cost":
        comma_separated_metrics += metric + ','```

**Comment by vakaobr** [comment]
I think the problem is related to new versions of sonarqube have introduced metrics with type STRING.

For now, we just found one metric called "new_development_cost" using this type.

We've managed to solve it with:

```if metric != "new_development_cost":
        comma_separated_metrics += metric + ','```

**Comment by vakaobr** [comment]
I think the problem is related to new versions of sonarqube have introduced metrics with type STRING.

For now, we just found one metric called "new_development_cost" using this type.

We've managed to solve it with:
```
if metric != "new_development_cost":
        comma_separated_metrics += metric + ','
```
